# Generated by Django 5.0.6 on 2024-06-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='room_number',
            new_name='class_number',
        ),
    ]
